### ISSUE TITLE
[TOPIC PROPOSAL] Accessibility

### ISSUE THREAD

**Issue by orlovedev** [raini-dev/raini#19]
## Accessibility

@vitasar, @tatoshko, @datapain add description of your vision for this topic, please. You've given your votes for it. For me, this area is terra incognita.

## Additional context

@vitasar, @tatoshko, @datapain are there any certifications that include this topic? It's OK if they don't but it would be nice to find one.

- [ ] The topic is part of certification

**Comment by priestine** [comment]
@tatoshko @vitasar @datapain I found the following set of certifications by IAAP:

* [Certified Professional in Accessibility Core Competencies (CPACC)](https://www.accessibilityassociation.org/cpacccertification)
* [Web Accessibility Specialist (WAS)](https://www.accessibilityassociation.org/wascertification)
* [International Certification of Accessibility Professionals - Built Environment (ICAP-BE)](https://www.accessibilityassociation.org/icapbeoverview)

I hope the materials can help in defining the scope of the workshop. Comment on whether you think one (or many) of these fits.

**Comment by vitasar** [comment]
Инфа про ally в [КБ](https://kb.epam.com/pages/viewpage.action?pageId=841008255)

**Comment by priestine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility](https://trello.com/c/mqCvuBDJ/5-accessibility)
