### ISSUE TITLE
[TOPIC PROPOSAL] Building eDSLs in functional TypeScript

### ISSUE THREAD

**Issue by YBogomolov** [raini-dev/raini#20]
## Building eDSLs in functional TypeScript

Business logic could be expressed in a limited subset of host language, leading to correct by construction, robust, optimisable code. This process is known as building eDSL – embedded domain-specific languages – and interpreting them, and is a widely used practice in functional languages like Haskell, Scala, OCaml. Still, this topic is terra incognita for many JS/TS developers.

During this workshop I will give an overview of two ways of building eDSLs in functional TypeScript using `fp-ts` library:
1. Free Monads
2. Tagless Final

Requirements:
- A notebook with code editor OR browser with CodeSandbox.
- Downloaded workshop template or cloned template for CodeSandbox.
- Understanding basic concepts of functional programming: immutability, totality, purity, function composition, least power principle, etc.
- Understanding what a monad and a functor are.

Activities:
1. Code demo, showing strong and weak sides of each approach
2. Q&A session after each section

Help needed:
1. Ideas of business domains for demo – eDSLs are showing their best sides in rather complicated domains like finance, so coming up with a clear, understandable and simplest possible example is a challenge.

## Additional context

- [ ] The topic is part of certification
- [ ] The topic extends existing or planned workshop
- [x] I would like to participate in organizing the workshop
- [x] I would like to be an istructor on this workshop

**Comment by priestine** [comment]
Thank you! Let's dig into this 😄

**Comment by priestine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Building eDSL](https://trello.com/c/3ynj1nyq/7-building-edsl)

**Comment by YBogomolov** [comment]
Template repo: https://github.com/YBogomolov/workshop-edsl-in-typescript

**Comment by priestine** [comment]
Great job, btw!

**Comment by priestine** [comment]
The workshop video is available @ https://youtu.be/8VFhePZZGdc
