### ISSUE TITLE
[Going serverless with AWS]: What will the workshop be about?

### ISSUE THREAD

**Issue by datapain** [raini-dev/raini#26]
Please help to resolve the issues below, as they will be fundamental to this workshop.

- [ ] What the scope of the "Going serverless"?
- [ ] What level is supposed?
- [ ] For which platforms?
- [ ] For which technologies?

**Comment by priestine** [comment]
I've got a few thoughts on this.

1. The theory should outline what Serverless is and how it is different from Serverful
2. The practice should walk the attendees through the process of migrating data to DynamoDB, queues to SQS, messages to SNS, as well as splitting the codebase to be compatible with AWS Lambda and setting up API Gateway.

The level requirements would depend on the codebase as well as how deep you will go in the theoretical part.

I would be glad to help with the last two questions yet I'm not sure I understand them completely. Could you expand/explain them?

**Comment by priestine** [comment]
For the practice, we can create a monolithic to-do list Node app with React front-end.

It should store data in a DB (e.g., SQLite), send emails about overdue items, provide a simple REST API for interaction and OAuth (Gmail can be used to simplify the implementation of sending emails). Alternatively, other OAuth can be used (e.g. GitHub) with services like Mailgun or Sendgrid for email.

It would have a relatively small codebase and it seems to be quite simple to decompose.

**Comment by priestine** [comment]
@datapain I would suggest you to create a proposal issue in https://github.com/orgs/raini-dev/projects/1, outline your ideas and expectations about the workshop and link this project board to that issue so that we don't get lost.

**Comment by AntonRatnick** [comment]
I think that we may move an application to serverless, I mean that you may take an existed application and adapt it for serverless.
If you don't have any application which may be moved. you may ask your colleagues and friends.

I think that if you do so, you will get answers to your questions, and you will create a real-world example of using serverless.

**Comment by priestine** [comment]
I think we can reuse @YBogomolov's domain model to actually implement ourselves a blogging platform. 😄

**Comment by priestine** [comment]
It's not the right place for the issue to exist as many things have changed since April.

So, @datapain, I suggest you take a look at the contribution guide and try to make it all the way through.
