### ISSUE TITLE
[WORKSHOP PROPOSAL] Reusable web components

### ISSUE THREAD

**Issue by AntonRatnick** [raini-dev/raini#41]
## Reusable web components
The idea to create components that can be easily used by various FE frameworks.
Different cases of usage like within CDN script or as npm package

- [ ] The workshop helps prepare for certification
- [x] The workshop extends existing or planned workshop

**Comment by priestine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reusable web components](https://trello.com/c/mr9RUQ3H/8-reusable-web-components)
